name: Fetch Cat Picture

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cat-picture-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch cat picture script
        env:
          CATS_API_KEY: ${{ secrets.CAT_API_KEY }}
        run: python fetch_cat_picture.py
