name: Hello World

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Greet and fail
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo "Hello, World"
      - name: Fail step
        run: exit 1